# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      # Group Django and all Django plugins together
      django-ecosystem:
        patterns:
          - "django"
          - "django-*"
        update-types:
          - "minor"
          - "patch"
      
      # Group AWS SDK packages
      aws-sdk:
        patterns:
          - "boto3*"
          - "botocore*"
      
      # Group testing/dev tools (minor and patch only)
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      
      # Catch-all for remaining minor and patch updates
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"